* Hypothesis
The objective of your data analysis is to test the following hypotheses:

** First Hypothesis - scene category effect
There is an effect of scene category (i.e., a difference between images showing
man-made vs. natural environments) on the amplitude of the N1 component, i.e. the
first major negative EEG voltage deflection.

** Second Hypothesis - image novelty
There are effects of image novelty (i.e., between images shown for the first time/new
vs. repeated/old images) within the time-range from 300–500 ms ...

a. on EEG voltage at fronto-central channels.
b. on theta power at fronto-central channels.
c. on alpha power at posterior channels.

** Third Hypothesis - "succesfully" detect old images
There are effects of successful recognition of old images (i.e., a difference between
old images correctly recognized as old [hits] vs. old images incorrectly judged as new
[misses]) ...

a. on EEG voltage at any channels, at any time.
b. on spectral power, at any frequencies, at any channels, at any time.

** Fourth Hypothesis - subsequent memory (?)
There are effects of subsequent memory (i.e., a difference between images that will
be successfully remembered vs. forgotten on a subsequent repetition) ...

a. on EEG voltage at any channels, at any time.
b. on spectral power, at any frequencies, at any channels, at any time.


* Processing scripts

Requirements [6/11]:
- [X] Transform all data to compressed data
- [X] Go through all subjects and extract evoked response potential (ERP) in specified timeframe (before & after event) for specific _code_
- [X] Save all extracted ERP for all subjects
- [X] Go through saved ERP of all subjects and create mean ERP across all subjects
- [X] Make trigger code more error prone/generic
- [X] Define (simply) _fronto-central_ channels (only for /second/ hypothesis)
- [ ] Extract theta & beta power from _one_ channel
- [ ] Extract theta & beta power from _any_ channel
- [ ] Extract spectral power from channel: _any_ frequency
- [ ] Extract spectral power from channel: at any time (?)
- [ ] Extract EEG voltage from channel: from zero to peak or peak to peak?

* Questions

- What/where are fronto-central channels? How many? -> [[file:/media/cygnuseco/ext4_files/research/EMP_data/EMP_data/channel_locations/chanlocs_besa.txt][manypipelines channel locations]]
